/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

ALTER TABLE `tb_user`
	ADD COLUMN `address` VARCHAR(500) NULL DEFAULT NULL COMMENT '地址' AFTER `balances`,
	ADD COLUMN `zip_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '邮编' AFTER `address`,
	ADD COLUMN `age` INT(3) NULL DEFAULT NULL COMMENT '年龄' AFTER `zip_code`,
	ADD COLUMN `sex` INT(1) NULL DEFAULT NULL COMMENT '性别' AFTER `age`;
